### ISSUE TITLE
plugin manager

### ISSUE THREAD

**Issue by ghost** [dllmusic/VCV_moDllz#1]
Hi!

today version 0.5.1 including the plugin manager got released. your plugins got the wrong download-link
pls fix that soonish.

copied from the log.txt
[warning] Could not get download URL for plugin moDllz

**Comment by dllmusic** [comment]
It may be that you are in Windows...? There's only Mac version for now... I just uploaded a new plugin and asked for help compiling Windows and Linux. It should work fine when I get those binaries...

**Comment by dllmusic** [comment]
I just updated the files. It should work as soon as the updates are cleared by the admin. Thanks

**Comment by ghost** [comment]
i just tried to merge your changes in the pull request and ended up getting an error from travis again

Failed: Zip entries should all be under a dir named moDllz but this entry was found: __MACOSX/

did you zip it with the finder? because i had this with another dev aswell... its best to use:
"make" and then "make dist" 
your makefile should create a zip archieve which works.

**Comment by dllmusic** [comment]
That's strange...I'm actually using "make dist"...
also... this is already working on VCV mac version... 
I deleted "moDllz" and "_MACOSX" folders in my Rack plugins, and after the "update plugins" moDllz shows up fine, and there is a _MACOSX folder with only "vcv-karatesnoopy-0.5.0".
I know that previously "moDllz" showed up there too, but not anymore.
Also, Rack doesn't try to re-download it every time (like before)
Maybe check out this procedure?
Thank you

**Comment by ghost** [comment]
![235465768](https://user-images.githubusercontent.com/31989694/34330072-b6c2bc68-e916-11e7-9753-b256060fc083.png)

I m not talking about the plugin folder :)
I was talking about your zip file for windows.. it contains a _MACOSX folder which shouldnt be in it...
btw we dont want ppl to do those changes.. it should install correctly.. if its already working with the mac version... thats fine (and good!)

I m gonna check everything tomorrow (monday) again.. to find a solution that it start working properly for all ;)

maybe i m compiling it for you  (on/for windows).. depends on how much time i will have tomorrow

**Comment by dllmusic** [comment]
Got it...I see!! I know what the problem was... If that was version 0.5.1-win ...I DID zip it on Mac finder, because I received that binary from another source and I wanted to check if everything was there. After checking I re did the zip from the Mac finder (instead of uploading the original). Sorry I wasn't aware of that issue...
I wont do that when receive the 0.5.2-win !! Thank you!
