### ISSUE TITLE
GUI must be reworked a bit...

### ISSUE THREAD

**Issue by DomiKamu** [dllmusic/VCV_moDllz#10]
OS: Windows 7 Pro SP1 x64, Windows 10 Pro (Redstone 3) x64.
VCV Rack v0.6.1
Plugin version 0.6.2 (commit 4165f04 on 5 Apr 2018).

Hi, about **MIDI Poly 16** and **MIDI to Dual CV** modules, maybe it's a good idea to rework (reorganize) their GUI in order to avoid text overlays (plz see screen capture).

Thanks in advance.

![modllz](https://user-images.githubusercontent.com/24851960/41909629-d1e06fec-7947-11e8-9984-6bb8c37af996.png)

**Comment by dllmusic** [comment]
Oh Thank you ... didn't realize about that...'because it was just Core MIDI
for mye system...
Just in time ...I'm about to release the Poly 8 MPE in a few days...

**Comment by DomiKamu** [comment]
You're welcome! of course I understand you're developing on Mac platform. Also be sure isn't urgent, it's only cosmetic. You'll can advise me in case you'd like some tests on Windows platform.

**Comment by dllmusic** [comment]
Updated. (+ new module) Thank you

**Comment by DomiKamu** [comment]
Absolutely remarquable stuff! Thanks a lot!!!
I close this issue, of course ;)
