### ISSUE TITLE
Cannot compile on Windows

### ISSUE THREAD

**Issue by caecos** [dllmusic/VCV_moDllz#12]
$ make
g++  -Wsuggest-override -std=c++11  -DSLUG=moDllz -fPIC -I../../include -I../../dep/include -DVERSION=0.6.4 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/MIDI8MPE.cpp.o src/MIDI8MPE.cpp
src/MIDI8MPE.cpp: In member function 'void MIDI8MPE::releaseNote(uint8_t, uint8_t, uint8_t)':
src/MIDI8MPE.cpp:334:67: error: no matching function for call to 'find(std::vector<unsigned char>::iterator, std::vector<unsigned char>::iterator, uint8_t&)'
   auto it = std::find(cachedNotes.begin(), cachedNotes.end(), note);
                                                                   ^
In file included from C:/msys64/mingw64/include/c++/7.3.0/bits/locale_facets.h:48:0,
                 from C:/msys64/mingw64/include/c++/7.3.0/locale:40,
                 from C:/msys64/mingw64/include/c++/7.3.0/iomanip:43,
                 from src/moDllz.hpp:4,
                 from src/MIDI8MPE.cpp:6:
C:/msys64/mingw64/include/c++/7.3.0/bits/streambuf_iterator.h:369:5: note: candidate: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^~~~
C:/msys64/mingw64/include/c++/7.3.0/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
src/MIDI8MPE.cpp:334:67: note:   '__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char> >' is not derived from 'std::istreambuf_iterator<_CharT>'
   auto it = std::find(cachedNotes.begin(), cachedNotes.end(), note);
                                                                   ^
src/MIDI8MPE.cpp:340:70: error: no matching function for call to 'find(std::vector<unsigned char>::iterator, std::vector<unsigned char>::iterator, uint8_t&)'
    auto it = std::find(cachedMPE[i].begin(), cachedMPE[i].end(), note);
                                                                      ^
In file included from C:/msys64/mingw64/include/c++/7.3.0/bits/locale_facets.h:48:0,
                 from C:/msys64/mingw64/include/c++/7.3.0/locale:40,
                 from C:/msys64/mingw64/include/c++/7.3.0/iomanip:43,
                 from src/moDllz.hpp:4,
                 from src/MIDI8MPE.cpp:6:
C:/msys64/mingw64/include/c++/7.3.0/bits/streambuf_iterator.h:369:5: note: candidate: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^~~~
C:/msys64/mingw64/include/c++/7.3.0/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
src/MIDI8MPE.cpp:340:70: note:   '__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char> >' is not derived from 'std::istreambuf_iterator<_CharT>'
    auto it = std::find(cachedMPE[i].begin(), cachedMPE[i].end(), note);
                                                                      ^
src/MIDI8MPE.cpp: At global scope:
src/MIDI8MPE.cpp:926:7: warning: 'virtual void PolyModeDisplay::draw(NVGcontext*)' can be marked override [-Wsuggest-override]
  void draw(NVGcontext* vg) {
       ^~~~
src/MIDI8MPE.cpp:1029:7: warning: 'virtual void MidiccDisplay::draw(NVGcontext* ' can be marked override [-Wsuggest-override]
  void draw(NVGcontext* vg) {
       ^~~~
src/MIDI8MPE.cpp:1089:7: warning: 'virtual void BlockChannel::draw(NVGcontext*)' can be marked override [-Wsuggest-override]
  void draw(NVGcontext* vg) {
       ^~~~
src/MIDI8MPE.cpp:1122:8: warning: 'virtual void springDataKnob::onMouseUp(rack::EventMouseUp&)' can be marked override [-Wsuggest-override]
   void onMouseUp(EventMouseUp &e){
        ^~~~~~~~~
make: *** [../../compile.mk:65: build/src/MIDI8MPE.cpp.o] Error 1

**Comment by dllmusic** [comment]
...try now.... I included a couple of links to vector and algorithm libraries . It may be the fix. ...in Mac it compiles without those (?)

**Comment by caecos** [comment]
Bingo...works fine...thanks...
