### ISSUE TITLE
issue with midi poly 16

### ISSUE THREAD

**Issue by Jairodallos** [dllmusic/VCV_moDllz#15]
hello pablo
i want to comment you somethig with this module

there is a problem with tempo sync

after the module is in sync whit an external clock (clocked from impromptu), when the music figures rotary button is changed the sync is loosed

the idea is to sync changes of this button in a music theme but is not possible

Can you comment if is my problem or if is any of the module?

thanks

**Comment by dllmusic** [comment]
Hi ! Sorry for the late reply...I'm gonna check into that for next update. I'm currently working on other modules, making use of the new polyphonic ports. Thank you

**Comment by dllmusic** [comment]
I need to redo many sections of that module, external sync reset etc is not working as intended...
Thank you
