### ISSUE TITLE
pitch bend channel might not be considered

### ISSUE THREAD

**Issue by NothanUmber** [dllmusic/VCV_moDllz#16]
As MIDI-CV is currently only supporting CC-1 and V/Oct from MIDI-CC is not considering pitch bend, I tried to "polyphonize" the MIDI 8 MPE module by adding several Merge modules, to create a poly output from the individual mono outputs.
The MIDI 8 MPE module's V/Oct outputs have the nice property that they add up the pitch information from the midi note events and from the pitch bend events, giving you an overall cv value that corresponds to the x position of the finger. The voices of the merged output of the eight V/Oct mono outputs don't seem to be as independent as they should. When I move one finger, changing pitch bend on one channel, the pitches of all other notes also seem to be affected. Probably the channel information of the initial pitch bend event somehow gets lost.

**Comment by dllmusic** [comment]
Hi there. for individual channel PitchBend info you need to set it in MPE mode...
On MPE mode you get the pitch bend from each channel AND the PitchBend from the master channel (applied to all). On regular poly modes you only get one pitch bend to all voices.
 I'm almost ready with a new version of the MIDI 8 MPE (now MIDI poly MPE). with polyphonic ports... It's gonna be up in the next few weeks. Thank you

**Comment by dllmusic** [comment]
Midi poly MPE handles per channel Pitch Bend with dedicated outputs for Voice and  Master channel. and direct internal to CV routings.
