### ISSUE TITLE
Features request: MIDIpolyMPE panic button and fixed MPE voice assignment

### ISSUE THREAD

**Issue by teknico** [dllmusic/VCV_moDllz#18]
I finally got around to trying the MIDIpolyMPE module with my Linnnstrument and it works nicely, thank you very much for it! I'm putting out two feature requests for your kind consideration.

1) adding a panic button, that deletes all voice associations and resets all outputs. Sometimes notes get stuck with MIDI, and having to initialize the module and reload a preset is cumbersome.

2) in MPE mode (or a new one), statically associating the available voice channels to MIDI channels (excluding the master one), so that notes on MIDI ch. 1 always get the first voice, ch. 2 always the second and so on.

Why? The Linnstrument has a mode called Channel Per Row ([Per-Split Settings, MIDI Mode](http://www.rogerlinndesign.com/ls-per-split-settings.html)) where MIDI channels are assigned statically to rows of the matrix. The playing becomes similar to that of a string instrument (not surprising, given that Roger Linn plays guitar :-) ), with each row becoming monophonic.

Static assignment then allows customizing the sound generation for each row, being now predictable which voice will sound for each row played. Kind of like a guitar synth, but without the strings. :-)

Thanks again for your work and consideration. Should you add a Donate link, I'd have a use for that.

**Comment by dllmusic** [comment]
Good to know you are using my module!
1.There’s already a panic. Just click on the midi panel ( as stated on the
manual)
2. What you say is exactly MPE..( right?) .... each cannel always gets the
same voice channel. Sobin your case each row will get its own voice. (If
you need to use midi ch 1 for voices just assign the master to 16)

I m updating a couple of things that are goong to be available soon (the
midi reset reseting the voice  leds and the LEARN mode before the entry
mode, so in case you receive unwanted controllers that get “learned” you
can still change the cc number after)

**Comment by teknico** [comment]
> 1.There’s already a panic. Just click on the midi panel ( as stated on the manual)

Oh. I guess you mean this sentence:

"MIDI input device settings. With click Reset and reconnect saved device if not disconnected on loading"

I didn't realize it meant that, by it works perfectly!

> 2. What you say is exactly MPE. ( right?).... each channel always gets the same voice channel.
> So in your case each row will get its own voice.
> (If you need to use midi ch 1 for voices just assign the master to 16)

That's what I did and it mostly works, but the assignment of MIDI channels to voices is not static. Sometimes MIDI channel 1 gets voice 4, or 7, or any other. If I can get notes on MIDI ch. 1 to always end up on voice 1 (both in the LEDs and the polyphonic outputs), then I can reliably treat each Linnstrument row as a guitar string, and  tweak its sound differently from the other "strings".

**Comment by dllmusic** [comment]
Ohh Yes, I forgot that I changed (in my last version) the mpe voice
allocation to dynamically adapt to voices received . I will fix that so
it’s fixed to the midi ch !

**Comment by dllmusic** [comment]
I did the dynamic voices to save cpu (instead of enabling 16ch on mpe
mode).... but I just figured out a way to dynamically adapt to voices from
the controller but keeping the midi channel locked to voice ch.
I will post an update this weekend.
Thanks for the suggestion.

**Comment by dllmusic** [comment]
if you are on Mac I can send you the fixed plugin file (to replace on the plugin folder) so you have it before the VCVrack plugin update

**Comment by teknico** [comment]
Thanks but I'm using Linux (Ubuntu 19.04). No hurry, the reset feature is helping things already.

**Comment by dllmusic** [comment]
1.1.6 just got released. Thanks

**Comment by teknico** [comment]
It works perfectly! It's awesome! Thank you so much! <3
