### ISSUE TITLE
MIDIpolyMDE Crashes VCVRack on save.

### ISSUE THREAD

**Issue by Logos-Coder** [dllmusic/VCV_moDllz#19]
MIDIpolyMDE crashes VCVRack after a file has been saved once, VCV has been closed, then opened again, then on any consecutive saves or exiting (saving the autosave). I am not sure what causes this, but I do know it this plugin.

[log.txt](https://github.com/dllmusic/moDllz/files/3722520/log.txt)

## specs:
OS: Debian 10 (buster)
kernel: 4.19.0-6
DE: xfce4 12
VCVRack: 1.1.5
Jack2 with pulseaudio passtrough

**Comment by dllmusic** [comment]
Thanks for reporting. I'll try to find the issue... (I cannot reproduce this on Mac though.)... but I will revise the code

**Comment by Logos-Coder** [comment]
I tried this on a clean Fedora vm and a clean Debian vm, and I did not run into a crash. So actually it is some weird edge case with the way my computer is setup. I will let  you know what is wrong once I find out but you probably don't have to change anything.

**Comment by dllmusic** [comment]
Ah! good to know. ... I was googling that segmentation error 11 on Linux and sometimes it's related to hardware or corrupted libraries. I also know that in many Win machines the auto-save / auto open crashes (but it works fine after 2 or 3 retries...without changing anything )  (?)
Anyway let me know if you encounter issues. Thank you.

**Comment by Logos-Coder** [comment]
I just logged in to my VCV account on the Debian vm, downloaded all the plugins, then the issue appeared. It seems to be some plugin conflicting with yours???? I don't know. 😕

FYI I built the plugin from scratch without installing anything else on the vm's until now.

**Comment by dllmusic** [comment]
Ok...I will check the code for bad pointers that could produce segmentation errors (..may be related to the midi driver)...  I will do this later because I'm working on a project until Nov. Thanks!

**Comment by dllmusic** [comment]
Whenever (and if you can)...you could help me out by checking my other module: MIDI dual CV, because it uses the same Midi driver... so if that one doesn't crash, it means that the issue is not on the Midi driver...(and viceversa). Thank you.

**Comment by Logos-Coder** [comment]
No Problem! I'll try to find something myself (if I can) and submit a pull request.

**Comment by Rcomian** [comment]
Was having the same issue, took a while to track down.
Looks like only 6 outputs were being reserved for the MM outputs, but 8 were being written.

https://github.com/dllmusic/moDllz/pull/20

**Comment by dllmusic** [comment]
Thank you to Jim Rcomian!! I hope plugin is stable now.
I already updated to 1.1.7 and it should be on Rack soon

**Comment by Rcomian** [comment]
No problem, this is why I like open source, hoping this comment doesn't reopen the bug ...

**Comment by Logos-Coder** [comment]
Thank you for finding this! I'm sorry I couldn't help I Just couldn't get a good debug environment, and Things got busy so I didn't have time.
