### ISSUE TITLE
MIDI Poly+MPE should not reattack the last note depressed

### ISSUE THREAD

**Issue by caoliver** [dllmusic/VCV_moDllz#22]
I often use MIDI Poly+MPE in mono to get correct functionality for the sustain pedal.  (Think holding a note while playing two other keyboards.)  One issue I see when in retrigger mode is that the last note gets reattacked when an older note is released.  Steps to recreate: 1) Set up a patch with MIDI Poly+MPE as your MIDI input connection.  2) Set the voice channels to 1.  3) Press and hold a key.  4) Press and hold a different key.  5) Release the first key.  The note playing gets reattacked.  This should only happen if the note is different.  The trouble is that this gives bogus duplicated notes when playing legato with retrigger active.

**Comment by dllmusic** [comment]
Thanks for reporting. I will check into this

**Comment by dllmusic** [comment]
I finally got back to this project and I'm about to release v2 with this fixed.
