### ISSUE TITLE
Impossible to ajust the voices mode in MIDI Poly + MPE

### ISSUE THREAD

**Issue by nesdnuma** [dllmusic/VCV_moDllz#23]
Hello,

I am trying to set the module to the MPE mode. But as soon as I move the value entry controls, the settings change constantly until I switch to another parameter (see attached GIF). Version used: 1.1.7/Rack 1.1.6/Win 64.

![module issue](https://user-images.githubusercontent.com/6513218/115380277-b235b380-a1d2-11eb-8c60-1967511df2cb.gif)

**Comment by dllmusic** [comment]
I cannot reproduce that error. The wheel comes back to zero when you release it .... it is supposed to rotate values while holding it ...and you can click + or - to move by one. (Same as all the other parameters)
