### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by phdsg** [dllmusic/VCV_moDllz#3]
really like your modules. thx. saw there was no linux build, so i made one:
[moDllz-0.5.3-lin.zip](https://github.com/dllmusic/VCV_moDllz/files/1600740/moDllz-0.5.3-lin.zip)

**Comment by Atavic** [comment]
:+1: at modules and build.

**Comment by dllmusic** [comment]
Hi! Sorry I just saw this now...(I will pay more attention to GitHub) Thank you. I'm almost done with a new module... I let you know. Thanks again!

**Comment by phdsg** [comment]
yeah, i'm already playing a little bit with that :)
watching commits and posting a new binary once you're ready.

**Comment by dllmusic** [comment]
Great!...I still need to fix stuff on TwinGlider... I will be done this weekend with 5.4 version + the new module....

**Comment by phdsg** [comment]
while you're still at it: the new module doesn't recall the "running" state when re-opening a saved patch.

**Comment by dllmusic** [comment]
Ok.cool... I will add that... I never thought about saving the running
state... Thanks!

**Comment by dllmusic** [comment]
Running state recalled now. But most important...there were some missing SVGs for the note buttons, so they didn't work. Now they should be fine... The initialization works now (with 8 live buttons, 4 sequence only, 2 Locked and 2 (exclusive)xLocked (polyphonic skips that note)
Still tweaking stuff anyway...

**Comment by dllmusic** [comment]
Version 0.5.4 is ready. Thanks

**Comment by phdsg** [comment]
trying to build current master on linux.
this error:
```
src/MIDIPoly.cpp: In member function ‘void MIDIPolyInterface::releaseNote(int)’:
src/MIDIPoly.cpp:480:67: error: no matching function for call to ‘find(std::__cxx11::list<int>::iterator, std::__cxx11::list<int>::iterator, int&)’
     auto it = std::find(noteBuffer.begin(), noteBuffer.end(), note);

```

**Comment by dllmusic** [comment]
Got it. Thanks. I will check that..(I'm not getting that error in
Xcode...not even a warning). But I also found another issue to fix.... I
will keep you posted. Thank you

**Comment by phdsg** [comment]
windows compile bails with the same msg.

**Comment by dllmusic** [comment]
Got it. I replaced that code... Still tweaking other stuff though. I will
post this afternoon. Thanks!!

**Comment by dllmusic** [comment]
It is ready... if you want to check it out. Thank you for your help!!

**Comment by phdsg** [comment]
nice one...

[moDllz-0.5.4-lin.zip](https://github.com/dllmusic/VCV_moDllz/files/1752139/moDllz-0.5.4-lin.zip)
`abe97ab6f8f204b8b3ee9b25bb3bec520fa099278fb9d07a82bc151b0e0ec733  moDllz-0.5.4-lin.zip
`

**Comment by dllmusic** [comment]
Great!! Thank you!!

**Comment by dllmusic** [comment]
Just some quick info ..while I'm preparing the manual.

Basically 16 buttons can be set to 4 different modes:
(white) play live notes,
(blue) play sequence only,
(red) trigger locked notes,
(orange) trigger locked notes exclusively (without playing that note on the
poly voices).

So...if you want, for example 4 voices of polyphony you need to set 12
buttons on Seq or Lock ( xLock too, but that makes the live poly to ignore
that note)

Buttons can <Learn> notes when they are in mode Seq, Lock or xLock...

**Comment by phdsg** [comment]
i already played a little bit with it, but right now i got too many other things rolling, so i'm waiting for a manual (which btw. the ones for your other modules are really nice)
