### ISSUE TITLE
moDllz-0.5.4-win build

### ISSUE THREAD

**Issue by phdsg** [dllmusic/VCV_moDllz#4]
[moDllz-0.5.4-win.zip](https://github.com/dllmusic/VCV_moDllz/files/1752160/moDllz-0.5.4-win.zip)

`005c8fe6df8d2b59c2b5a1b1c9ac226f0ddb96903d8fee0b0b1b983ce0fc0a68 *moDllz-0.5.4-win.zip`

**Comment by dllmusic** [comment]
Thank you!!... I will start moving all this to 0.6 now!

**Comment by dllmusic** [comment]
Manual is up. Thanks!
https://drive.google.com/file/d/12kjCLSeyaaqXEvfS1c4HcnfrrbHeQ0ot/view

**Comment by phdsg** [comment]
printed and only found one typo...
![motypo](https://user-images.githubusercontent.com/33329578/36635211-82f4a60a-19b1-11e8-8c6d-cad2f13b3ea6.PNG)

**Comment by dllmusic** [comment]
👍thanks. Will fix it

**Comment by dllmusic** [comment]
Fixed. Thanks!
