### ISSUE TITLE
MIDI Poly16 Seq Arpeggiator (0.5.4): VCV Rack crashes

### ISSUE THREAD

**Issue by DomiKamu** [dllmusic/VCV_moDllz#5]
OS: Windows 7 Pro SP1, Windows 10 Pro "Redstone 3". all French-localized.
Rack v0.5.1 (installable version), moDllz v0.5.4 plugin.

Hi,

Sometimes, but not always, VCV Rack crashes as soon as I add MIDI Poly16 Seq Arpeggiator module into rack. Also, this may occur when reloading .vcv file (or autosave), or when deleting the module from rack ("Del" key). Any case: no other module into Rack during our investigations.

I'm not alone, two French FB friends having same behaviors. Having tested from a clean/fresh Windows 10, no other plugins installed (only Core, embedded within VCV Rack).

Regards,

Dominique

**Comment by dllmusic** [comment]
I will check it out. Do you have a crash log? Thank you

**Comment by phdsg** [comment]
just rechecked and tried the things mentioned, can't reproduce here. but from the described behavior i have a suspicion, let's see the log.txt or console output.

**Comment by DomiKamu** [comment]
[log.txt](https://github.com/dllmusic/VCV_moDllz/files/1756146/log.txt)
The last crash I've Poly16 and TwinGlider (no cables) - log.txt above - but it doesn't show anything useful, crash on removing... TwinGlider first (untouched Poly16).

Other attempt: from new Rack (Ctrl+N): instancied Poly16 and TwinGlider, no cables, no other modules, I can delete TwinGlider, but in this scenario, VCV Rack crashes as soon as I press "Del" key over Poly16, unfortunately "log.txt" was empty!

I don't have console output (I'm using regular/installable VCV Rack 0.5.1, don't have debug console - don't know if they're command-line switches to bring a debug console).

Regards,
Dominique.

**Comment by dllmusic** [comment]
I'm trying to reproduce this ...but sadly I don't have a Windows system. (Mac).
 I can load ...delete.. quit Rack. Autosaved patch loads fine...I loaded up to 10 instances of Poly16 plus some Twingliders too... and I don't get the crash. I also tried with/wout MIDI devices too.
But I noticed that sometimes I get the Reset sequencer Led on...(meaning that the button is "pressed"on load...) I will check this out..

I googled back this link about finding Win 10 crash log...
https://www.digitalmastersmag.com/magazine/tip-of-the-day-how-to-find-crash-logs-on-windows-10/

**Comment by phdsg** [comment]
i vaguely remember seeing crash behavior like this where rack dies while saving to autosave.vcv.
can't remember the plugin tho.
iirc starting rack again after the crash had a popup with some json error msg.

**Comment by DomiKamu** [comment]
Many plugins (modules) - any brand, any module, **including mine** (Ohmer Modules) may crash Rack while autosaving - every 5 seconds (memory segmentation issues, in general, like ton of Windows apps during... Windows XP era). On MacOS, memory management (and other things) are totally different. Unfortunately I don't have MacOS (nor Linux) to do similar tests (for investigations).

**Comment by DomiKamu** [comment]
json accesses + autosave during module deletion (or instanciations, too) maybe are the culprits. I don't understand the autosave, and why it can't be disabled via a simple on/off button from toolbar (except if you recompile a custom Rack for personal usage)

**Comment by dllmusic** [comment]
Thanks for the info. I will try to find out more about that...
I'm updating the code to 0.6 anyway, so there's a lot of testing to be done. 
Maybe to pinpoint the issue you could compile a testing version skipping the json..?
MIDIpoly.cpp lines 359 ~ 399 ... (sorry I cannot do it for win)

**Comment by DomiKamu** [comment]
You're welcome! as soon as source are migrated against 0.6.0dev and ready (probably on separate branch of your/this repo), I'll can test moDllz modules on my Windows platform, be sure it will be with pleasure!

EDIT: I'll take a look for current 0.5.4 source code (current release for Rack 0.5.1 about lines 359~399 from MIDIpoly.cpp - I'm git cloning... ;) - **Your PDF is fantastic, looking very nice and pro!**

Confused about logs (I've understood "log.txt" generated by VCV Rack, not Windows apps logs, sorry)

Dominique (Camus)
Greetings from Chartres, France

**Comment by DomiKamu** [comment]
Having many warnings (but no error) while compiling v0.5.4, mostly about "RtMidi.h" (override suggestions). Attached win-compile-log.zip (containing **win-compile-log.txt**, TXT can't be added direcly as attachment) it will better - IMO - than copy/paste into reply (console messages are unreadable).

[win-compile-log.zip](https://github.com/dllmusic/VCV_moDllz/files/1756729/win-compile-log.zip)

**_REPORT/INVESTIGATIONS FROM WINDOWS:_**
It's strange: by compiling from source (git clone), Windows 7 platform, now **I cannot reproduce** issue I've mentionned when I've opened this issue.

Tests (and working in both cases) against official/installable VCV Rack 0.5.1, either:
- 1/ after I've removed json functions (lines 359 to 399).
- 2/ then when compiled full version (unaltered) of "MIDIpoly.cpp" source file.

Assuming I can close this issue, by this way.
Honestly I don't understand, the mysteries of computer science (lol)

Dominique.

Don't hesitate to contact me for 0.6.0dev testing purposes (really, your modules are interesting, impressive PFD manual, clean source code, like a professional I love!):
- GitHub : https://github.com/DomiKamu/Ohmer-Modules (you'll can open an issue)
_my 060dev branch:_ https://github.com/DomiKamu/Ohmer-Modules/tree/060dev
- Facebook : https://www.facebook.com/dominique.camus.505

**Comment by DomiKamu** [comment]
Just three personal recommendations, if you permit me:
1/ About tags, avoid UTILITY_TAG as long as possible, they're used for very basic modules (mutes, sums).
2/ Concerning MIDI to Dual CV interface, you'll can add EXTERNAL_TAG (like MIDI modules from Core).
3/ Typos: displayed name for Poly would be (IMHO) **MIDI Poly 16 Seq Arpeggiator** (missing space between Poly and 16, like its GUI). Same principle for Dual for first module (D instead of d).

Updated "moDllz.cpp" including recommendations (into attached zip file, I'm not too familiar with GitHub).
[moDllz.zip](https://github.com/dllmusic/VCV_moDllz/files/1756806/moDllz.zip)

**Comment by dllmusic** [comment]
Sorry I m off my computer... just saw this on my phone. Thank you so much
for your help! I will correct the tag and the name. I m available if you
need Mac versions

**Comment by DomiKamu** [comment]
Don't worry!
Have you seen modified moDllz.cpp, attachement in my previous message (tags and displayed name fixes I've submitted)?

**Comment by dllmusic** [comment]
... I don't think I have that attachment. I can do those corrections on
v06... I just started with that. Thank you

**Comment by DomiKamu** [comment]
You're welcome, of course nothing is urgent, we can wait for next upgrade (based on Rack v0.6).

To be honest with you, I've compiled my Windows binary (plugin.dll) - as custom - using fixed tags & displayed module names) ;) of course, Be sure I'll don't share anything, remaining as "internal" usage, assuming it's your stuff, but not mine.

Don't hesitate if you need anything I'll can do it!
Dom.
