### ISSUE TITLE
Binaries in repository

### ISSUE THREAD

**Issue by cschol** [dllmusic/VCV_moDllz#7]
The binary .zip files are committed to the repository in the `dist` directory. They should be removed from the repository (preferred) or moved to another directory. If one runs `make clean` for a fresh build the `dist` directory is removed by the `Makefile` and the repository shows as having changes (deleted files).

**Comment by dllmusic** [comment]
I put 0.5.4 bin zips in dist_054 dir. 
...Where should I  place version 0.6 zips when ready?

**Comment by cschol** [comment]
It is generally not a good practice to put binaries in the source code repository. I would create a GitHub "Release" (Releases tab) and attach the binaries to that release so people can download them.

**Comment by dllmusic** [comment]
Got it! Fixing it now. Thank you

**Comment by cschol** [comment]
Awesome. Thank you!

**Comment by dllmusic** [comment]
Hi..I just compiled v0.6.0 Mac..can you please help me out with Win / Lin  ...(or do you know someone?)  
Thanks!!

**Comment by cschol** [comment]
Andrew will take care of the build for the binaries on all platforms. See [API Update Thread](https://github.com/VCVRack/Rack/issues/258#issuecomment-376293898).

**Comment by dllmusic** [comment]
Oh good. Thank you!

**Comment by dllmusic** [comment]
I just updated sources in my repo. Also renamed it so it is the actual slug. Where should I report this?.. Thank you
