### ISSUE TITLE
segfault macos: moDllz::MIDIPolyInterface

### ISSUE THREAD

**Issue by dirkleas** [dllmusic/VCV_moDllz#8]
adding/removing moDllz::MIDIPolyInterface via package manager in a patching workflow session causes segfault on macos w/ rack 0.6.0.  trace shows macos MIDI issues -- would you like a stack trace?

```
terminating with uncaught exception of type RtMidiError: MidiInCore::initialize: error creating OS-X MIDI client object (-50).
```

**Comment by dllmusic** [comment]
I cannot reproduce this error...but I'll check into this...Thanks.
What MIDI devices are you using?

**Comment by dirkleas** [comment]
no midi devices connected during offending test case

**Comment by dllmusic** [comment]
I'm updating all modules in a few days, they will be compiled with Rack 6.1, that has resolved MIDI issues... let's see. Thank you

**Comment by dllmusic** [comment]
Updated...let me know if it works now.. Thank you

**Comment by dirkleas** [comment]
prior test cases updated for the new release and they all pass/run as expected on macos -- thanks for the fix and module awesomeness!
