### ISSUE TITLE
MIDI interface modules crashing Rack 0.6.1 on Win10

### ISSUE THREAD

**Issue by sbcook0** [dllmusic/VCV_moDllz#9]
Adding "MIDI Poly 16" or "MIDI to dual CV interface" to VCV 0.6.1 (last modified Jun 18 2018) on Win10 Home 1803 build 17134.112 crashes the program. Typical Windows log entry:
Faulting application name: Rack.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: Rack.exe, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000000000007661d
Faulting process id: 0x116c
Faulting application start time: 0x01d408c911042a33
Faulting application path: C:\Program Files\VCV\Rack\Rack.exe
Faulting module path: C:\Program Files\VCV\Rack\Rack.exe
Report Id: cc94b772-848d-4a22-afad-78462c21c26c
Faulting package full name: 
Faulting package-relative application ID:

**Comment by dllmusic** [comment]
I guess my MIDI modules need to be recompiled on 6.1... I'm almost done
with another MIDI module Poly8+MPE.. so they will be updated soon. Thanks

**Comment by dllmusic** [comment]
Updated. Compiled w 0.6.1. Let me know if it works fine now... Thank you

**Comment by sbcook0** [comment]
I see v0.6.4 in the plug-in manager. This version works OK..
